<<<<<<< HEAD
sudo: required 
services:
    - docker

before_install:
    - docker pull node:8-onbuild

install:
    - docker build -t probot-hello .

script:
    - docker run --rm probot-hello npm run test
    - docker run --rm probot-hello npm run lint
=======
language: node_js
node_js:
  - "8.3"
>>>>>>> 385148a8e35e01653aebc241402b534661ebae83
